### ISSUE TITLE
Update to use MarkDig

### ISSUE THREAD

**Issue by michael-hawker** [Hosch250/MarkdownViewer#3]
Really cool project idea here! Think the idea is to read Markdown into a RichTextBox for WPF?

Just wanted to let you know we're trying to remove the Parsers from the Toolkit and use MarkDig instead, see our issue tracking that here: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3200

**Comment by Hosch250** [comment]
Thank you for the update. I have another closed-source project I'll need to update as well.

Yes, you are right about the project idea.

**Comment by Hosch250** [comment]
There are a few Markdown-to-WPF projects listed on the MarkDig site. Archiving this project as I wasn't actively maintaining it anyway.
